---
title: "John Mensah_FIFA World Cup Analysis"
format: html
editor: visual
---

```{r}
library(tidyverse)
fifa_data <- read.csv("players_20.csv")

```

## The interrelationship among players' individual ratings.

```{r}
player_rate <- fifa_data %>% select(, 45:78)

player_mean.rate <- data.frame(attacking = rowMeans(player_rate[, 1:5]),
                               skill = rowMeans(player_rate[, 6:10]),
                               movement = rowMeans(player_rate[, 11:15]),
                               power = rowMeans(player_rate[, 16:20]),
                               mentality = rowMeans(player_rate[, 17:26]),
                               defending = rowMeans(player_rate[, 27:29]))


library(ggplot2)
install.packages("ggcorrplot")
library(ggcorrplot)

  
# Computing correlation matrix
correlation_matrix <- round(cor(player_mean.rate),3)
  
# Computing correlation matrix with p-values
corrp.mat <- cor_pmat(player_mean.rate)
  
# Adding correlation significance level
ggcorrplot(correlation_matrix, hc.order =TRUE, type ="lower", 
           p.mat = corrp.mat, lab = T) + theme_classic() + ylab("") + xlab("")

```

## How do these individual player ratings contribute to the overall rating of the player?

```{r}
library(glmmTMB)
library(MuMIn)
library(DHARMa)
library(broom.mixed)


player_mean.rate$overall.rating <- fifa_data$overall
player_mean.rate$nationality <- fifa_data$nationality
hist(player_mean.rate$overall.rating)

mod <- glmmTMB(overall.rating ~ attacking + skill + movement + power + mentality + defending+ (1|nationality), family=gaussian(), player_mean.rate)
summary(mod)


res = simulateResiduals(mod)
plot(res)

options(na.action = "na.fail")
dd <- dredge(mod)
tt = data.frame(dd)
subset(dd, delta < 4)

summary(model.avg(dd))
mod1 <- get.models(dd, 1)[[1]]
summary(mod1)


```

```{r}
 mod_vars = all.vars( formula(mod1) )[-1] 

preddat_fun = function(data, allvars, var) {
     sums = summarise_at(data, 
                         vars( one_of(allvars), -one_of(var) ), 
                         median) 
     cbind( select_at(data, var), sums)
}

head( preddat_fun(player_mean.rate, mod_vars, "attacking") )

pred_dats = mod_vars %>%
     set_names() %>%
     map( ~preddat_fun(player_mean.rate, mod_vars, .x) )
str(pred_dats)

head( augment(mod1, newdata = pred_dats[[1]], se_fit = TRUE))

preds = pred_dats %>%
     map(~augment(mod1, newdata = .x, se_fit = TRUE) ) %>%
     map(~mutate(.x, 
                 lower = .fitted - 2*.se.fit,
                 upper = .fitted + 2*.se.fit,
                 pred = .fitted ) )

str(preds$attacking)
preds <- preds[-6]
ggplot(data = preds$attacking, aes(x = attacking, y = pred) ) +
     geom_line(size = 1) +  geom_point() +
     geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .25, color = "blue", fill="blue") +
     geom_rug(sides = "b") +
     theme_classic(base_size = 10) +
     labs(x = "Players attacking score",
          y = "Overall rating") 

xlabs = c("Player's attacking rating (%)", 
          "Player's defending rating (%)",
          "Player's mentality rating (%)", 
          "Player's power rating (%)",
          "Players's skill rating (%)")

pred_plot = function(data, variable, xlab) {
     ggplot(data, aes(x = .data[[variable]], y = pred) ) +
          geom_line(size = 1) +
          geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .25) +
          geom_rug(sides = "b") +
          theme_classic(base_size = 10) +
          labs(x = xlab,
               y = "Overall rating (%)") 
}

pred_plot(preds[[1]], mod_vars[1], xlabs[1])


mod_vars1 = all.vars( formula(mod1) )[c(-1,-7)] 

all_plots = pmap( list(preds, mod_vars1, xlabs), pred_plot)
all_plots

cowplot::plot_grid(plotlist = all_plots,
          labels = "AUTO",
          align = "hv")


```
